### ISSUE TITLE
Unable to enable module: 'String' is a special class name

### ISSUE THREAD

**Issue by maartendeblock** [ueberbit/role_delegation#1]
Hi, I'm unable to enable the module
Error: Cannot use Drupal\Component\Utility\String as String because 'String' is a special class name in
/modules/contrib/role_delegation/role_delegation.module, line 14

Drupal: 8.0.2
PHP: 7.0.0

**Comment by webflo** [comment]
I fixed the issue in commit 3a8e15d, please try again. Thanks!

**Comment by maartendeblock** [comment]
Tnx, I can install now.
